FROM python:3.8.8

ENV PYTHONUNBUFFERED 1
WORKDIR /app

ADD . /plasmadonorapp

COPY ./requirements.txt /app/requirements.txt

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

COPY . /app